CREATE TABLE `associados` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(40) NOT NULL,
  `CPF` varchar(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME` (`NOME`),
  UNIQUE KEY `CPF` (`CPF`)
) ENGINE=InnoDB AUTO_INCREMENT=147 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pautas` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(40) NOT NULL,
  `SESSAO` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME` (`NOME`)
) ENGINE=InnoDB AUTO_INCREMENT=146 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `votacoes` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_PAUTA` int NOT NULL,
  `ID_ASSOCIADO` int NOT NULL,
  `VOTO` int DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKad5dgb45l9gnuk9u9qxs5ns4r` (`ID_ASSOCIADO`),
  KEY `FKi8g9qulab67i9viso0pl8m7j6` (`ID_PAUTA`),
  CONSTRAINT `FKad5dgb45l9gnuk9u9qxs5ns4r` FOREIGN KEY (`ID_ASSOCIADO`) REFERENCES `associados` (`ID`),
  CONSTRAINT `FKi8g9qulab67i9viso0pl8m7j6` FOREIGN KEY (`ID_PAUTA`) REFERENCES `pautas` (`ID`),
  CONSTRAINT `votacoes_ibfk_1` FOREIGN KEY (`ID_PAUTA`) REFERENCES `pautas` (`ID`),
  CONSTRAINT `votacoes_ibfk_2` FOREIGN KEY (`ID_ASSOCIADO`) REFERENCES `associados` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=145 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
